### ISSUE TITLE
github.com/pbenner/autodiff/simple should have ConstScalar arguments wherever possible

### ISSUE THREAD

**Issue by shutej** [pbenner/autodiff#1]
I've started using this library and I've been very impressed so far, thanks for making it!

One thing I've noticed: it'd be a lot easier to use if the "simple" package took ConstScalar arguments wherever possible.  This would allow const-y arguments to be put into expressions with the Simple package, and only after proving that a loop is hot with the profiler would you go back and remove the allocations.

**Comment by pbenner** [comment]
Removed autodiff/simple because it doesn't fit well with the new interface.
