### ISSUE TITLE
The `Import` functions cannot support large files

### ISSUE THREAD

**Issue by shutej** [pbenner/autodiff#4]
The `Import` functions are currently limited to lines that are 64K long:

https://golang.org/pkg/bufio/#pkg-constants

When that line length is exceeded, for instance, a DenseRealVector will silently fail to read and return a 0-length result.  In my testing, this means it'll load a file with 3,000 floats but not 4,000.

This wouldn't be a problem, you could simply store the vector as a column vector on disk with newlines, if it weren't for this statement:

https://github.com/pbenner/autodiff/blob/master/vector_dense_barereal.go#L363

Would you consider it to be a bug if the vector `Import` were to be permissive and load either column or row vectors?  If not, that statement could be deleted.

**Comment by pbenner** [comment]
Thanks for reporting this issue! The problem should be fixed now.
